-- MySQL Script generated by MySQL Workbench
-- lun. 04 sept. 2017 11:40:17 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Helloplatdy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Helloplatdy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Helloplatdy` DEFAULT CHARACTER SET utf8 ;
USE `Helloplatdy` ;

-- -----------------------------------------------------
-- Table `Helloplatdy`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Helloplatdy`.`User` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(50) NULL,
  `user_pwd` VARCHAR(255) NULL,
  `user_salt` VARCHAR(255) NULL,
  `user_mail` VARCHAR(50) NULL,
  `user_role` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Helloplatdy`.`Restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Helloplatdy`.`Restaurant` (
  `id_restaurant` INT NOT NULL AUTO_INCREMENT,
  `restaurant_name` VARCHAR(255) NULL,
  `restaurant_pwd` VARCHAR(255) NULL,
  `restaurant_salt` VARCHAR(255) NULL,
  `restaurant_mail` VARCHAR(50) NULL,
  `restaurant_street` VARCHAR(150) NULL,
  `restaurant_town` VARCHAR(50) NULL,
  `restaurant_zip_code` INT NULL,
  `restaurant_horaire_monday` VARCHAR(255) NULL,
  `restaurant_horaire_tuesday` VARCHAR(45) NULL,
  `restaurant_horaire_wednesday` VARCHAR(45) NULL,
  `restaurant_horaire_thursday` VARCHAR(45) NULL,
  `restaurant_horaire_friday` VARCHAR(45) NULL,
  `restaurant_horaire_saturday` VARCHAR(45) NULL,
  `restaurant_horaire_sunday` VARCHAR(45) NULL,
  `restaurant_category` VARCHAR(100) NULL,
  `restaurant_description` LONGTEXT NULL,
  PRIMARY KEY (`id_restaurant`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Helloplatdy`.`Discount_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Helloplatdy`.`Discount_code` (
  `id_discount_code` INT NOT NULL AUTO_INCREMENT,
  `discount_code` VARCHAR(50) NULL,
  `discount_code_offer` VARCHAR(100) NULL,
  `discount_code_description` LONGTEXT NULL,
  `discount_code_start` DATETIME NULL,
  `discount_code_finish` DATETIME NULL,
  `id_restaurant` INT NOT NULL,
  PRIMARY KEY (`id_discount_code`, `id_restaurant`),
  INDEX `fk_Discount_code_Restaurant1_idx` (`id_restaurant` ASC),
  CONSTRAINT `fk_Discount_code_Restaurant1`
    FOREIGN KEY (`id_restaurant`)
    REFERENCES `Helloplatdy`.`Restaurant` (`id_restaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Helloplatdy`.`Feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Helloplatdy`.`Feedback` (
  `id_feedback` INT NOT NULL AUTO_INCREMENT,
  `feedback_rating` INT NULL,
  `feedback_title` VARCHAR(50) NULL,
  `feedback_comments` LONGTEXT NULL,
  `feedback_date` VARCHAR(45) NULL,
  `id_restaurant` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_feedback`, `id_restaurant`, `id_user`),
  INDEX `fk_Feedback_Restaurant1_idx` (`id_restaurant` ASC),
  INDEX `fk_Feedback_User1_idx` (`id_user` ASC),
  CONSTRAINT `fk_Feedback_Restaurant1`
    FOREIGN KEY (`id_restaurant`)
    REFERENCES `Helloplatdy`.`Restaurant` (`id_restaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Feedback_User1`
    FOREIGN KEY (`id_user`)
    REFERENCES `Helloplatdy`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Helloplatdy`.`Discount_code_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Helloplatdy`.`Discount_code_has_User` (
  `id_discount_code` INT NOT NULL,
  `id_restaurant` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_discount_code`, `id_restaurant`, `id_user`),
  INDEX `fk_Discount_code_has_User_User1_idx` (`id_user` ASC),
  INDEX `fk_Discount_code_has_User_Discount_code1_idx` (`id_discount_code` ASC, `id_restaurant` ASC),
  CONSTRAINT `fk_Discount_code_has_User_Discount_code1`
    FOREIGN KEY (`id_discount_code` , `id_restaurant`)
    REFERENCES `Helloplatdy`.`Discount_code` (`id_discount_code` , `id_restaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Discount_code_has_User_User1`
    FOREIGN KEY (`id_user`)
    REFERENCES `Helloplatdy`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
